#ifndef _MSG_ACTION_DATA_DEFINE_H_
#define _MSG_ACTION_DATA_DEFINE_H_

enum LKS_LIGHT_STATUS
{
    LKS_LIGHT_OFF = 0x00,
    LKS_LIGHT_PASSIVE = 0x01,
    LKS_LIGHT_STANDBY = 0x02,
    LKS_LIGHT_ACTIVE = 0x03,
    LKS_LIGHT_TAKE_OFF_REQUEST = 0x04,
    LKS_LIGHT_SAFE_STOP = 0x05,
    LKS_LIGHT_TEMP_ERROR = 0x06,
    LKS_LIGHT_PERMANENT_ERROR = 0x07
};

#endif //!_MSG_ACTION_DATA_DEFINE_H_
